server:
  host: 127.0.0.1
  port: 8083


mongo:
  host: 10.62.216.29
  port: 27017
  databaseName: Resource
  username: root
  password: example

mysql:
  host: 10.62.216.29
  port: 3306
  dbName: ResourceShare
  user: root
  password: "lwm"

redis:
  host: 10.62.216.29
  dbName: 1
  port: 6379
  user: root
  password: 