server:
  host: 127.0.0.1
  port: 8081



minio:
  endpoint: 121.37.228.161:9000
  accessKeyID: 6t9XgA7VkE0va0xCvZmj
  secretAccessKey: Zl5wiCQNR179Hzq5zFwMz2fYxMpGpSdmKbmwLkvw
  bucketName: analysis
