server: 
  host: 192.168.31.156
  port: 8084


redis:
  host: 192.168.31.27
  dbName: 1
  port: 6379
  user: root
  password: 

mysql:
  host: 192.168.31.27
  port: 3306
  dbName: ResourceShare
  user: root
  password: "lwm"
