server:
  host: 10.62.37.21
  port: 8084

rpcserver:
  servername: UserServer
  host: 10.62.37.21
  port: 50051


etcd:
  addrs:
    - 121.37.228.161:2379 #etcd 集群地址这里是单节点
  timeout: 5 #最大时间


jwt:
  key: lwmhaoshuai

email: 
  host: "smtp.qq.com"
  port: 465
  userName: "3191711818@qq.com"
  password: "piokodbqjuiaddba"
  from: "3191711818@qq.com"

redis:
  host: 10.62.216.29
  dbName: 1
  port: 6379
  user: root
  password: 

mysql:
  host: 10.62.216.29
  port: 3306
  dbName: ResourceShare
  user: root
  password: "lwm"
